root_path: "/home/demet/Desktop/Chest_Dataset/Chest_Dataset_Resize"

## Chest14: /home/demet/Desktop/Chest_Dataset/Chest_Dataset_Resize
## CheXpert: /home/demet/Desktop/CheXpert-v1.0-small

mode: "train"

data:
  size: [224, 224]

model:
  model_type: "cbam"
  number_classes: 15

## chex_small
## chest14

train:
  name: "chest14"
  data_path: "/home/demet/Desktop/Chest_Dataset/Chest_Dataset_Resize"
  start_epoch: 0
  end_epoch: 31
  batch: 32
  num_workers: 0
  chkpnt_step: 5
  loss:
    classification:
    metric:

  learning_rate:
    momentum: 0.9
    decay: 0.5
    base_rate: 0.0001
    steps: 10

## Chest14: /home/demet/Desktop/Chest_Dataset/Chest_Dataset_Resize
## CheXpert: /home/demet/Desktop/CheXpert-v1.0-small
## chex_small
## chest14

test:
  name: "chest14"
  dataset_path: "/home/demet/Desktop/Chest_Dataset/Chest_Dataset_Resize"
  checkpoint_path: "/home/demet/PycharmProjects/thesis/training_logs/chest14/cbam_lr0.0001_bs32/20.pth"
  batch: 64
  num_workers: 0


experiment_name: "cel"
log_dir: "/home/demet/PycharmProjects/thesis/training_logs"



  # batchsize = [64]  # [64, 128, 256, 512]
  # learningrate = [1e-3, 1e-4, 1e-5]
